[package]
name = "matrix"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "matrix"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.35.0"
lazy_static = "1.5.0"
image = { version = "0.25.4", default-features = false, features = ["gif", "jpeg", "png"] }
